name: Parallel tests
on: push
jobs:
  registerFlow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerFlow
      
      - name: Cypress Test Report
      - uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Register flow
          path: cypress/reports/html
    
    addToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        if: always() # To generate reports for failures tests also.
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCartFlow
      
      - name: Cypress Test Report
        if: always() # To generate reports for failures tests also.
      - uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Add To Cart Flow
          path: cypress/reports/html